name = "buddy"
main = "src/index.js"
compatibility_date = "2024-09-09"

# 로컬 개발용 환경변수 (로컬 개발 시에만 사용)
# [vars]
# 로컬 개발 시 Mock 키 사용
# OPENAI_API_KEY = "MOCK_KEY_FOR_TESTING"
# CLAUDE_API_KEY = "MOCK_KEY_FOR_TESTING"

[env.production]
name = "buddy"

# Environment variables (set via wrangler secret put)
# OPENAI_API_KEY - OpenAI API key for LLM integration
# CLAUDE_API_KEY - Anthropic Claude API key for LLM integration

# KV Namespaces
[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "65fd50e7ae6b467b8b3a86fbb51e8df0"
preview_id = "70c9d54c5cef48baa210ebcaebed75b1"

[[env.production.kv_namespaces]]
binding = "CHAT_HISTORY"
id = "65fd50e7ae6b467b8b3a86fbb51e8df0"

[[env.production.d1_databases]]
binding = "DB"
database_name = "buddy-db"
database_id = "28a02194-a330-4bfb-b863-d15315f59a6c" 
