name = "buddy"
main = "src/index.js"
compatibility_date = "2024-09-09"

# 로컬 개발용 환경변수 (로컬 개발 시에만 사용)
# [vars]
# 로컬 개발 시 Mock 키 사용
# OPENAI_API_KEY = "MOCK_KEY_FOR_TESTING"
# CLAUDE_API_KEY = "MOCK_KEY_FOR_TESTING"

[env.production]
name = "buddy"

# Environment variables (set via wrangler secret put)
# OPENAI_API_KEY - OpenAI API key for LLM integration
# CLAUDE_API_KEY - Anthropic Claude API key for LLM integration
# CHAT_HISTORY - Cloudflare KV namespace for chat history 